CREATE DATABASE templatedb;

CREATE TABLE users (
  _id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL CHECK (LENGTH(password) >= 8)
);
